### ISSUE TITLE
Example without dependent variables

### ISSUE THREAD

**Issue by samedii** [Statisticat/LaplacesDemon#14]
Is there already a simple example using no dependent variables? I.e. J=0, no data X, etc. If so, I haven't managed to find it.

Great library and love the demon theme!

**Comment by samedii** [comment]
My attempt, maybe I'm very off but if not then maybe it will save some work

	library('fExtremes')
	library('LaplacesDemon')

	set.seed(666)

	N <- 100 
	J <- 0  

	y <- rgpd(N, 0.3, 0, 0.3)

	mon.names <- 'LP'
	parm.names <- as.parm.names(list(ksi=0, sigma=0))  
	pos.ksi <- grep('ksi', parm.names)  
	pos.sigma <- grep('sigma', parm.names)  

	MyData <- list(J=J, N=N, mon.names=mon.names,  
	    parm.names=parm.names, pos.ksi=pos.ksi, pos.sigma=pos.sigma, y=y)  

	is.data(MyData)

	Model <- function(parm, Data)  
	{  

		ksi <- parm[Data$pos.ksi]  
		sigma <- interval(parm[Data$pos.sigma], 1e-100, Inf)  
		parm[Data$pos.sigma] <- sigma  

		ksi.prior <- dnormv(ksi, 0.3, 0.1, log=TRUE)
		sigma.prior <- dlnorm(sigma, log(0.3), 0.1, log=TRUE)

		LL <- sum(dgpd(Data$y, ksi, 0, sigma, log=TRUE))  

		LP <- LL + sigma.prior + ksi.prior  
		Modelout <- list(LP=LP, Dev=-2*LL, Monitor=LP,  
			yhat=rgpd(N, ksi, 0, sigma), parm=parm)  #yhat is wrong here?
		return(Modelout)  
	}  

	Initial.Values <- c(0.5, 0.5)

	iter <- 1000
	Fit <- LaplacesDemon(Model, Data=MyData, Initial.Values,
	                     Covar=matrix(c(1,0,0,1),nrow=2,ncol=2), Iterations=iter, Status=iter/10, Thinning=1,
	                     Algorithm="RWM", CPUs=16, Packages=c('fExtremes'))


	Consort(Fit)

**Comment by Statisticat** [comment]
I'm wondering if the Revision example is what you are looking for? It is usually the simplest introductory example where a distribution is updated with new information.

**Comment by samedii** [comment]
Thank you! :)
