### ISSUE TITLE
Specs list has to be in a certain order?

### ISSUE THREAD

**Issue by samedii** [Statisticat/LaplacesDemon#16]
Could you use for example:

    all(c("n","Periodicity") %in% names(Specs))

or is there a reason for having them in a certain order? Just wanting to check first

**Comment by Statisticat** [comment]
Good question. The drawback of writing a zillion lines of code is trying to keep it all straight, meaning reasons for doing things a certain way. I remember this coming up some time ago, and there was a reason that order mattered, but I cannot see one now. So, let's try it, thumbs up :)

**Comment by samedii** [comment]
Cool! I'm sure the advantages outweigh the drawbacks :)
I am new to this and I haven't tried my changes. I'll make sure to learn how to if there's a next time(!)
