### ISSUE TITLE
Graph showing incorrect number of iterations(?)

### ISSUE THREAD

**Issue by samedii** [Statisticat/LaplacesDemon#18]
In plot.demonoid and plot.demonoid.ppc

Most obvious with LP
![image](https://cloud.githubusercontent.com/assets/1872050/6593820/fc910b0a-c7db-11e4-8040-3b8d228cb20c.png)

![image](https://cloud.githubusercontent.com/assets/1872050/6593827/0fd45352-c7dc-11e4-8ba4-dcdbe3418a34.png)

Can provide code if you want it (github doesn't let me attach r-files and I don't want to bloat the issue)

**Comment by samedii** [comment]
I saw it being called adaptations (in proposal variance). Maybe it should just be changes to this?

**Comment by Statisticat** [comment]
Please email the code that generated this to software@bayesian-inference.com.

From what I see, I'm guessing whichever sampler updated this used thinning, so it updated 1,000 iterations and retained only 33 thinned samples?

**Comment by samedii** [comment]
Yes, you're correct. I didn't realize that. Maybe "iterations" still is a misnomer though? Could possibly be easier to understand if it was called "samples" or if it was changed to the "real" iterations

**Comment by Statisticat** [comment]
That's a good point. "Thinned Samples" might describe it better? I'll noodle with that today.

**Comment by samedii** [comment]
Yes thinned samples sounds good :)

**Comment by Statisticat** [comment]
Updated
