### ISSUE TITLE
Incorrect plot.demonoid docs?

### ISSUE THREAD

**Issue by samedii** [Statisticat/LaplacesDemon#19]
In plot.demonoid: "Kernel density plots depict the marginal posterior distribution. There is no distributional assumption about this density."

While we can see that a normal distribution is fitted to every point from the samples which is what the function "density" uses as default:
"kernel, a character string giving the smoothing kernel to be used ... with default 'gaussian'"

Did you mean no distributional assumption as in the combination of all these normal distributions?

**Comment by Statisticat** [comment]
This is a good point, too. What is meant is that there are not distributional assumptions about marginal posterior distributions, although kernel density estimation makes some assumptions. I'll tinker today with re-wording this for clarity.

**Comment by Statisticat** [comment]
Updated
