### ISSUE TITLE
LaplaceApproximation crashes

### ISSUE THREAD

**Issue by Bramstang** [Statisticat/LaplacesDemon#26]
Hi!
First of all, great library, it has been immensely helpful! However, I just ran into my first problems:

When trying to use the LaplaceApproximation function to get some initial values for MCMC, it works fine with simulated data from the GP distribution, or with just an array with some constants (as shown below), but when I try to replace it with real data, the function crashes with the error 

    Error in if (ncol(post) == length(Data[["parm.names"]])) { : 
     argument is of length zero

### Code snippet

    library('fExtremes')
    
    # the real data
    y1.notWorking <- c(0.680479826, 0.834319527, 8.346295841, 5.995002776, 4.352043929, 1.489911907, 6.010654490, 2.207262761, 2.275154673, 0.570300158, 0.202745210, 0.090004148, 1.191616766, 0.895410886,  0.811598149, 0.170998904, 1.244466873, 0.642077215, 0.236139179, 0.607376610, 0.250772494,  0.052077218, 0.923914127, 0.149591350, 4.157827151, 1.584570217, 0.363462206, 0.536275728,  1.621832105, 5.564475995, 2.058529265, 3.022265914, 0.551941867, 0.679467546, 1.812142823,  1.847738052, 0.195467572, 2.170105417, 0.590643823, 1.545189069, 0.317728274, 0.074444023,  0.091144110, 0.135074358, 0.342410594, 0.914059511, 1.158908855, 0.477790942, 0.050994599,  0.045259324, 2.572776606, 0.296758022, 0.121515237, 1.272219392, 0.466429235, 0.006694483,  0.464222256, 0.981728012, 0.790200689, 0.718128994, 0.172278991, 0.363751926, 2.554385583,  0.879005761, 1.171842678, 1.302507070, 0.172604188, 0.289417765, 0.774916080, 0.363312355,  0.015660860, 0.838553029, 0.371115004, 0.054769402, 1.088041343, 0.920902518, 0.248735058,  0.914445716, 1.021383651, 4.635315549, 1.191856705, 2.808004138, 0.158874934, 4.058112873,  6.668514298, 3.559800559, 4.188428893, 1.429344545, 3.568594795, 0.965190946, 1.361458081,  0.862901578, 2.586595295, 0.393180549, 0.046858758, 1.191075279, 2.934825709, 0.351503373,  4.936389079, 2.339453264, 3.444661549, 0.348477941, 0.129175371, 0.227260999, 0.618675469, 0.179037535, 0.648450744, 1.664738967, 0.133824743, 0.733241738, 0.337253508, 0.168203088, 0.199504623, 0.427743804, 4.873664902, 4.789226753, 2.562329851, 2.584696371, 2.389382837, 2.354414361, 2.782480315, 1.220831530, 2.006292965, 1.043601665, 2.409132811, 2.051571087, 1.026701836, 7.476918666, 0.228597135, 2.985846418, 0.347809545, 0.717890558, 0.339273125, 1.298309786, 4.123831971, 4.559441396, 0.410796947, 4.231675922, 11.173204297, 3.201423546, 0.394912547, 1.611002385, 0.194820298, 0.667873319, 1.394510545, 0.555342186, 1.995475751, 1.412916739, 1.361273554, 0.010941801, 2.346446999, 3.303646762, 1.752051077, 0.187354237, 1.804272287, 0.686421925, 2.988145399, 0.113147055, 3.167798673, 5.921161826, 0.621288515, 3.090358651, 0.290239343, 5.122835661, 1.938829685, 1.811385729, 0.350445825, 0.877098937, 1.852925126, 0.041251594, 0.353575919, 1.184708164, 0.605404628, 0.657042127, 0.651249213, 0.153879933, 2.258514026, 0.029406398, 0.279767085, 1.006033739, 0.034093041, 3.832096639, 0.722345857, 0.245565731, 2.354871802, 2.928983536, 0.570905432, 1.624721754, 1.397614499, 0.925470333, 0.319133830, 0.055278492, 1.265702206, 0.225148903, 0.245263227, 0.285082733, 0.024041657, 0.341462178, 1.114953017, 0.138555754, 0.125704653, 0.592810957, 4.781703117, 0.007591685, 0.228909642, 1.024713471)
    N = length(y1.notWorking)

    y2.notWorking <- c(rep(2,N))    
    y1.working <- c(rep(0.2,N))
    
    
    y <- y1.notWorking
    
    mon.names <- list('LP')
    parm.names <- as.parm.names(list(ksi=0, sigma=0))  
    pos.ksi <- grep('ksi', parm.names)  
    pos.sigma <- grep('sigma', parm.names)  
    
    MyData <- list(N=N, mon.names=mon.names,  
                   parm.names=parm.names, pos.ksi=pos.ksi, pos.sigma=pos.sigma, y=y)  
    
    Model <- function(parm, Data)  
    {  
      
      ksi <- parm[Data$pos.ksi]  
      sigma <- interval(parm[Data$pos.sigma], 1e-100, Inf)  
      parm[Data$pos.sigma] <- sigma  
      
      ksi.prior <- dnormv(ksi, 0, 100, log=TRUE)  
      sigma.prior <- dhalfcauchy(sigma, 25, log=TRUE)  
      
      LL <- sum(dgpd(Data$y, xi=ksi, mu=0, beta=sigma, log=TRUE))  # fExtremes
      LP <- LL + sigma.prior + ksi.prior  
      Modelout <- list(LP=LP, Dev=-2*LL, Monitor=LP,  
                       yhat=rgpd(N, xi=ksi, mu=0, beta=sigma), # ksi, mu, sigma              
                       parm=parm) 
      return(Modelout)  
    }  
    
    Initial.Values <- c(0.5, 0.5)
    
    LaplaceApproxWithPrior <- LaplaceApproximation(Model=Model, parm=Initial.Values, Data=MyData, Interval=1.0E-6,
                                                   Iterations=100, Method="SPG", Samples=N, CovEst="Hessian",
                                                   sir=FALSE, Stop.Tolerance=1.0E-5, CPUs=1, Type="PSOCK")

**Comment by Statisticat** [comment]
Hi, and many thanks for reporting this!

The GPD functions from fExtremes are problematic in LaplacesDemon. Given proper distribution functions, LaplacesDemon works like a charm, and I've used LaplaceApproximation for years with real data sets.

In another issue available on GitHub, I created my own dgpd function according to Wkipedia's formula, and get quite different answers from the function in fExtremes. I also noticed that rgpd returns a data frame, not a vector or matrix, and that could be problematic later.

Most distribution functions from other sources work great here, but GPD from fExtremes is a problem.

Currently, I am currently putting some debugging code in so users are aware when their models are generating non-finite values and so forth.

**Comment by Bramstang** [comment]
Hmm okey, I will try the dgpd you wrote as well as one from a different package and see if I can get it to work. Thanks!

**Comment by Bramstang** [comment]
Okay, so I compared the dgpd functions from the two packages fExtremes and lmomco to the one you supplied in issue #20 (the one from Wikipedia). I noticed that you made a typo in the last term of the density (as can be seen in the comments in the below code) but after I fixed that and also added support for ksi = 0 (also from Wikipedia) all of the three dgpd functions agree perfectly:

### Testing dgpd functions from different packages

    rm(list=ls())  # clear variables
    cat("\014")  # clear console
    
    # install.packages('lmomco')
    # install.packages('fExtremes')
    
    library(fExtremes)
    library(lmomco)
    
    dgpd.ld <- function(x, mu, sigma, zeta, log=FALSE) #Wikipedia
    {
      #https://en.wikipedia.org/wiki/Generalized_Pareto_distribution
      x <- as.vector(x)
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      zeta <- as.vector(zeta)
      if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
      NN <- max(length(x), length(mu), length(sigma), length(zeta))
      x <- rep(x, len=NN); mu <- rep(mu, len=NN)
      sigma <- rep(sigma, len=NN); zeta <- rep(zeta, len=NN)
      z <- (x - mu) / sigma
      dens <- log(1 / sigma) + log(1 + zeta * z)*(-(1 / (zeta + 1)))
    #   dens <- log(1 / sigma) + log(1 + zeta * z)*(-1/zeta - 1) # from wikipedia
      if(log == FALSE) dens <- exp(dens)
      return(dens)
    }
    
    dgpd.ld.fixed <- function(x, mu, sigma, zeta, log=FALSE) #Wikipedia
    {
      #https://en.wikipedia.org/wiki/Generalized_Pareto_distribution
      x <- as.vector(x)
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      zeta <- as.vector(zeta)
      if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
      NN <- max(length(x), length(mu), length(sigma), length(zeta))
      x <- rep(x, len=NN); mu <- rep(mu, len=NN)
      sigma <- rep(sigma, len=NN); zeta <- rep(zeta, len=NN)
      z <- (x - mu) / sigma
      
      dens <- exp(-z) # for z = 0
      
      # for zeta != 0
      nonZeroZetaIndex <- zeta != 0
      dens[nonZeroZetaIndex] <- 1/sigma[nonZeroZetaIndex] * (1 + zeta[nonZeroZetaIndex]*z[nonZeroZetaIndex])^(-1/zeta[nonZeroZetaIndex] - 1)
      
      if(log == TRUE) dens <- log(dens)
      return(dens)
    }
    
    x <- c(0.680479826, 0.834319527, 8.346295841, 5.995002776, 4.352043929, 1.489911907, 6.010654490, 2.207262761, 2.275154673, 0.570300158, 0.202745210, 0.090004148, 1.191616766, 0.895410886,  0.811598149, 0.170998904, 1.244466873, 0.642077215, 0.236139179, 0.607376610, 0.250772494,  0.052077218, 0.923914127, 0.149591350, 4.157827151, 1.584570217, 0.363462206, 0.536275728,  1.621832105, 5.564475995, 2.058529265, 3.022265914, 0.551941867, 0.679467546, 1.812142823,  1.847738052, 0.195467572, 2.170105417, 0.590643823, 1.545189069, 0.317728274, 0.074444023,  0.091144110, 0.135074358, 0.342410594, 0.914059511, 1.158908855, 0.477790942, 0.050994599,  0.045259324, 2.572776606, 0.296758022, 0.121515237, 1.272219392, 0.466429235, 0.006694483,  0.464222256, 0.981728012, 0.790200689, 0.718128994, 0.172278991, 0.363751926, 2.554385583,  0.879005761, 1.171842678, 1.302507070, 0.172604188, 0.289417765, 0.774916080, 0.363312355,  0.015660860, 0.838553029, 0.371115004, 0.054769402, 1.088041343, 0.920902518, 0.248735058,  0.914445716, 1.021383651, 4.635315549, 1.191856705, 2.808004138, 0.158874934, 4.058112873,  6.668514298, 3.559800559, 4.188428893, 1.429344545, 3.568594795, 0.965190946, 1.361458081,  0.862901578, 2.586595295, 0.393180549, 0.046858758, 1.191075279, 2.934825709, 0.351503373,  4.936389079, 2.339453264, 3.444661549, 0.348477941, 0.129175371, 0.227260999, 0.618675469, 0.179037535, 0.648450744, 1.664738967, 0.133824743, 0.733241738, 0.337253508, 0.168203088, 0.199504623, 0.427743804, 4.873664902, 4.789226753, 2.562329851, 2.584696371, 2.389382837, 2.354414361, 2.782480315, 1.220831530, 2.006292965, 1.043601665, 2.409132811, 2.051571087, 1.026701836, 7.476918666, 0.228597135, 2.985846418, 0.347809545, 0.717890558, 0.339273125, 1.298309786, 4.123831971, 4.559441396, 0.410796947, 4.231675922, 11.173204297, 3.201423546, 0.394912547, 1.611002385, 0.194820298, 0.667873319, 1.394510545, 0.555342186, 1.995475751, 1.412916739, 1.361273554, 0.010941801, 2.346446999, 3.303646762, 1.752051077, 0.187354237, 1.804272287, 0.686421925, 2.988145399, 0.113147055, 3.167798673, 5.921161826, 0.621288515, 3.090358651, 0.290239343, 5.122835661, 1.938829685, 1.811385729, 0.350445825, 0.877098937, 1.852925126, 0.041251594, 0.353575919, 1.184708164, 0.605404628, 0.657042127, 0.651249213, 0.153879933, 2.258514026, 0.029406398, 0.279767085, 1.006033739, 0.034093041, 3.832096639, 0.722345857, 0.245565731, 2.354871802, 2.928983536, 0.570905432, 1.624721754, 1.397614499, 0.925470333, 0.319133830, 0.055278492, 1.265702206, 0.225148903, 0.245263227, 0.285082733, 0.024041657, 0.341462178, 1.114953017, 0.138555754, 0.125704653, 0.592810957, 4.781703117, 0.007591685, 0.228909642, 1.024713471)
    
    ksi <- 0.3
    sigma <- 1
    mu <- 0
    
    y1 <- as.vector(fExtremes::dgpd(x, xi=ksi, mu = mu, beta = sigma))
    
    y2 <- lmomco::pdfgpa(x, vec2par(c(mu, sigma, -ksi), type='gpa'))
    
    y3 <- dgpd.ld(x, mu=mu, sigma=sigma, zeta=ksi)
    
    y4 <- dgpd.ld.fixed(x, mu=mu, sigma=sigma, zeta=ksi)
    
    plot(c(rep(x,4)),c(y1, y2, y3, y4))
    
    all.equal(y1,y2)
    
    all.equal(y1,y4)
    
    all.equal(y2,y4)

### Trying LaplaceApproximation with the 3 different dgpd's
However, when I try to run LaplaceApproximation, both dgpd.ld.fixed and dgpd gives me the same error as in my original post, while lmomco just gives me a result that doesn't fit the data at all (-0.8 something shape parameter):


     rm(list=ls())  # clear variables
     cat("\014")  # clear console
     library('fExtremes')
     library('LaplacesDemon')
     library('lmomco')
        
        
    y <- c(0.680479826, 0.834319527, 8.346295841, 5.995002776, 4.352043929, 1.489911907, 6.010654490, 2.207262761, 2.275154673, 0.570300158, 0.202745210, 0.090004148, 1.191616766, 0.895410886,  0.811598149, 0.170998904, 1.244466873, 0.642077215, 0.236139179, 0.607376610, 0.250772494,  0.052077218, 0.923914127, 0.149591350, 4.157827151, 1.584570217, 0.363462206, 0.536275728,  1.621832105, 5.564475995, 2.058529265, 3.022265914, 0.551941867, 0.679467546, 1.812142823,  1.847738052, 0.195467572, 2.170105417, 0.590643823, 1.545189069, 0.317728274, 0.074444023,  0.091144110, 0.135074358, 0.342410594, 0.914059511, 1.158908855, 0.477790942, 0.050994599,  0.045259324, 2.572776606, 0.296758022, 0.121515237, 1.272219392, 0.466429235, 0.006694483,  0.464222256, 0.981728012, 0.790200689, 0.718128994, 0.172278991, 0.363751926, 2.554385583,  0.879005761, 1.171842678, 1.302507070, 0.172604188, 0.289417765, 0.774916080, 0.363312355,  0.015660860, 0.838553029, 0.371115004, 0.054769402, 1.088041343, 0.920902518, 0.248735058,  0.914445716, 1.021383651, 4.635315549, 1.191856705, 2.808004138, 0.158874934, 4.058112873,  6.668514298, 3.559800559, 4.188428893, 1.429344545, 3.568594795, 0.965190946, 1.361458081,  0.862901578, 2.586595295, 0.393180549, 0.046858758, 1.191075279, 2.934825709, 0.351503373,  4.936389079, 2.339453264, 3.444661549, 0.348477941, 0.129175371, 0.227260999, 0.618675469, 0.179037535, 0.648450744, 1.664738967, 0.133824743, 0.733241738, 0.337253508, 0.168203088, 0.199504623, 0.427743804, 4.873664902, 4.789226753, 2.562329851, 2.584696371, 2.389382837, 2.354414361, 2.782480315, 1.220831530, 2.006292965, 1.043601665, 2.409132811, 2.051571087, 1.026701836, 7.476918666, 0.228597135, 2.985846418, 0.347809545, 0.717890558, 0.339273125, 1.298309786, 4.123831971, 4.559441396, 0.410796947, 4.231675922, 11.173204297, 3.201423546, 0.394912547, 1.611002385, 0.194820298, 0.667873319, 1.394510545, 0.555342186, 1.995475751, 1.412916739, 1.361273554, 0.010941801, 2.346446999, 3.303646762, 1.752051077, 0.187354237, 1.804272287, 0.686421925, 2.988145399, 0.113147055, 3.167798673, 5.921161826, 0.621288515, 3.090358651, 0.290239343, 5.122835661, 1.938829685, 1.811385729, 0.350445825, 0.877098937, 1.852925126, 0.041251594, 0.353575919, 1.184708164, 0.605404628, 0.657042127, 0.651249213, 0.153879933, 2.258514026, 0.029406398, 0.279767085, 1.006033739, 0.034093041, 3.832096639, 0.722345857, 0.245565731, 2.354871802, 2.928983536, 0.570905432, 1.624721754, 1.397614499, 0.925470333, 0.319133830, 0.055278492, 1.265702206, 0.225148903, 0.245263227, 0.285082733, 0.024041657, 0.341462178, 1.114953017, 0.138555754, 0.125704653, 0.592810957, 4.781703117, 0.007591685, 0.228909642, 1.024713471)
    N <- length(y)
    
    dgpd.ld.fixed <- function(x, mu, sigma, zeta, log=FALSE) #Wikipedia
    {
      #https://en.wikipedia.org/wiki/Generalized_Pareto_distribution
      x <- as.vector(x)
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      zeta <- as.vector(zeta)
      if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
      NN <- max(length(x), length(mu), length(sigma), length(zeta))
      x <- rep(x, len=NN); mu <- rep(mu, len=NN)
      sigma <- rep(sigma, len=NN); zeta <- rep(zeta, len=NN)
      z <- (x - mu) / sigma
      
      dens <- exp(-z) # for z = 0
      
      # for zeta != 0
      nonZeroZetaIndex <- zeta != 0
      dens[nonZeroZetaIndex] <- 1/sigma[nonZeroZetaIndex] * (1 + zeta[nonZeroZetaIndex]*z[nonZeroZetaIndex])^(-1/zeta[nonZeroZetaIndex] - 1)
      
      if(log == TRUE) dens <- log(dens)
      return(dens)
    }
    
    
    mon.names <- list('LP')
    parm.names <- as.parm.names(list(ksi=0, sigma=0))  
    pos.ksi <- grep('ksi', parm.names)  
    pos.sigma <- grep('sigma', parm.names)  
    
    MyData <- list(N=N, mon.names=mon.names,  
                   parm.names=parm.names, pos.ksi=pos.ksi, pos.sigma=pos.sigma, y=y)  
    
    is.data(MyData)
    
    Model <- function(parm, Data)  
    {  
      
      ksi <- parm[Data$pos.ksi]  
      sigma <- interval(parm[Data$pos.sigma], 1e-100, Inf)  
      parm[Data$pos.sigma] <- sigma  
      
      ksi.prior <- dnormv(ksi, 0, 100, log=TRUE)  
      sigma.prior <- dhalfcauchy(sigma, 25, log=TRUE)  
      
        LL <- sum(dgpd.ld.fixed(Data$y, mu=0, sigma=sigma, zeta=ksi, log=TRUE)) 
      #LL <- sum(log(lmomco::pdfgpa(Data$y, vec2par(c(0, sigma, -ksi), type='gpa'))))
    #   LL <- sum(fExtremes::dgpd(Data$y,  xi=ksi,mu=0, beta=sigma, log=TRUE))
      
      LP <- LL + sigma.prior + ksi.prior
      Modelout <- list(LP=LP, Dev=-2*LL, Monitor=LP,  
                       yhat=rgpd(N, xi=ksi, mu=0, beta=sigma), # ksi, mu, sigma              
                       parm=parm) 
      return(Modelout)  
    }
    
    Initial.Values <- c(0.5, 0.5)
    
    LaplaceApproxWithPrior <- LaplaceApproximation(Model=Model, parm=Initial.Values, Data=MyData, Interval=1.0E-6,
                                                   Iterations=100, Method="SPG", Samples=N, CovEst="Hessian",
                                                   sir=FALSE, Stop.Tolerance=1.0E-5, CPUs=1, Type="PSOCK")
    
    ML_ksi <- LaplaceApproxWithPrior$Summary1[1,1]
    ML_sigma <- LaplaceApproxWithPrior$Summary1[2,1]

**Comment by Statisticat** [comment]
Thanks for catching that, I didn't look beyond their pdf box on the right. Now that I/we are, notice the support box above it. Unless I'm missing something, and it's early with coffee in hand, I think you will need to constrain parameters to proper support, given y (x in Wiki), within the model function before evaluating the density.

Hopefully that should do the trick.

**Comment by Bramstang** [comment]
That did indeed do the trick, I really should have read the whole thing on Wikipedia :(

Everything works fine now, all three versions of the dgpd gives consistent results both in the LaplaceApproximation and the MCMC I use afterwards. Thanks!

**Comment by Statisticat** [comment]
Glad that worked out!

I know the issue is closed, but since you're probably more familiar with this density than I am, I was wondering if you could look this over really quick. If you're good with it, then I'll include GPD in the package, because (if I got it right), this should catch and prevent that problem:

dgpd <- function(x, mu, sigma, zeta, log=FALSE) #Wikipedia
     {
     x <- as.vector(x)
     mu <- as.vector(mu)
     sigma <- as.vector(sigma)
     zeta <- as.vector(zeta)
     if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
     NN <- max(length(x), length(mu), length(sigma), length(zeta))
     x <- rep(x, len=NN); mu <- rep(mu, len=NN)
     sigma <- rep(sigma, len=NN); zeta <- rep(zeta, len=NN)
     zeta.ge.0 <- which(zeta >= 0)
     zeta.lt.0 <- which(zeta < 0)
     if(any(mu[zeta.ge.0] > x[zeta.ge.0]) |
          any(mu[zeta.lt.0] < x[zeta.lt.0] + sigma[zeta.lt.0] /
          zeta[zeta.lt.0]))
          stop("Parameter mu is outside of support.")
     z <- (x - mu) / sigma
     zeta0 <- which(zeta == 0)
     zeta1 <- which(zeta != 0)
     dens <- rep(NA, NN)
     dens[zeta0] <- -z[zeta0]
     dens[zeta1] <- log(1/sigma[zeta1]) + log(1 + zeta[zeta1] *
          zeta[zeta]) * (-1/zeta[zeta1] - 1)
     if(log == FALSE) dens <- exp(dens)
     return(dens)
     }

**Comment by Bramstang** [comment]
I'm already on my way home, it's late afternoon here in Sweden, but I will
look at it first thing tomorrow!
Den 19 mar 2015 16:29 skrev "Statisticat" <notifications@github.com>:

**Comment by Statisticat** [comment]
Argh, found a typo, here's the correct version:

dgpd <- function(x, mu, sigma, zeta, log=FALSE)
     {
     x <- as.vector(x)
     mu <- as.vector(mu)
     sigma <- as.vector(sigma)
     zeta <- as.vector(zeta)
     if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
     NN <- max(length(x), length(mu), length(sigma), length(zeta))
     x <- rep(x, len=NN); mu <- rep(mu, len=NN)
     sigma <- rep(sigma, len=NN); zeta <- rep(zeta, len=NN)
     zeta.ge.0 <- which(zeta >= 0)
     zeta.lt.0 <- which(zeta < 0)
     if(any(mu[zeta.ge.0] > x[zeta.ge.0]) |
          any(mu[zeta.lt.0] < x[zeta.lt.0] + sigma[zeta.lt.0] /
          zeta[zeta.lt.0]))
          stop("Parameter mu is outside of support.")
     z <- (x - mu) / sigma
     zeta0 <- which(zeta == 0)
     zeta1 <- which(zeta != 0)
     dens <- rep(NA, NN)
     dens[zeta0] <- -z[zeta0]
     dens[zeta1] <- log(1/sigma[zeta1]) + log(1 + zeta[zeta1] *
          zeta[zeta1]) * (-1/zeta[zeta1] - 1)
     if(log == FALSE) dens <- exp(dens)
     return(dens)
     }

**Comment by Bramstang** [comment]
Hi again! So, a few things:

1. I found a second typo in the last term of zeta[zeta1]. It says zeta
twice but one of them should be z instead, here's the fixed version

dgpd <- function(x, mu, sigma, zeta, log=FALSE)
    {
      x <- as.vector(x)
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      zeta <- as.vector(zeta)
      if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
      NN <- max(length(x), length(mu), length(sigma), length(zeta))
      x <- rep(x, len=NN); mu <- rep(mu, len=NN)
      sigma <- rep(sigma, len=NN); zeta <- rep(zeta, len=NN)
      zeta.ge.0 <- which(zeta >= 0)
      zeta.lt.0 <- which(zeta < 0)
      if(any(mu[zeta.ge.0] > x[zeta.ge.0]) |
           any(mu[zeta.lt.0] < x[zeta.lt.0] + sigma[zeta.lt.0] /
                 zeta[zeta.lt.0]))
        stop("Parameter mu is outside of support.")
      z <- (x - mu) / sigma
      zeta0 <- which(zeta == 0)
      zeta1 <- which(zeta != 0)
      dens <- rep(NA, NN)
      dens[zeta0] <- -z[zeta0]
      dens[zeta1] <- log(1/sigma[zeta1]) + log(1 + zeta[zeta1] *
                                                 z[zeta1]) *
(-1/zeta[zeta1] - 1)
      if(log == FALSE) dens <- exp(dens)
      return(dens)
    }

2. After fixing that, it appears to be correct for zeta != 0 (it agrees
with both fExtremes and lmomco, as well as Matlab). But if zeta == 0 it
does not take the sigma parameter into account (i.e. changing sigma has no
effect whatsoever if zeta == 0. I can't figure out why though, maybe it's
just the R syntax that I'm unfamiliar with (learned R last week). So that
needs to be fixed!

3. Very minor thing, but maybe use ksi or xi instead of zeta, since that is
what they use on wikipedia and most other sources I've seen :)

4. It would also be great to have a function for generating random GP
numbers in LD, to be used in prediction and such!

2015-03-19 17:35 GMT+01:00 Statisticat <notifications@github.com>:

**Comment by Statisticat** [comment]
Below is both your corrected dgpd (also changed as suggested from shape zeta to xi), as well as an rgpd function.

dgpd <- function(x, mu, sigma, xi, log=FALSE)
     {
     x <- as.vector(x)
     mu <- as.vector(mu)
     sigma <- as.vector(sigma)
     xi <- as.vector(xi)
     if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
     NN <- max(length(x), length(mu), length(sigma), length(xi))
     x <- rep(x, len=NN); mu <- rep(mu, len=NN)
     sigma <- rep(sigma, len=NN); xi <- rep(xi, len=NN)
     xi.ge.0 <- which(xi >= 0)
     xi.lt.0 <- which(xi < 0)
     if(any(mu[xi.ge.0] > x[xi.ge.0]) |
          any(mu[xi.lt.0] < x[xi.lt.0] + sigma[xi.lt.0] / xi[xi.lt.0]))
          stop("Parameter mu is outside of support.")
     z <- (x - mu) / sigma
     xi0 <- which(xi == 0)
     xi1 <- which(xi != 0)
     dens <- rep(NA, NN)
     dens[xi0] <- -z[xi0]
     dens[xi1] <- log(1/sigma[xi1]) + log(1 + xi[xi1] *
          z[xi1]) * (-1/xi[xi1] - 1)
     if(log == FALSE) dens <- exp(dens)
     return(dens)
     }
rgpd <- function(n, mu, sigma, xi)
     {
     mu <- as.vector(mu)
     sigma <- as.vector(sigma)
     xi <- as.vector(xi)
     if(any(sigma <= 0)) stop("The sigma parameter must be non-negative.")
     mu <- rep(mu, len=n); sigma <- rep(sigma, len=n)
     xi <- rep(xi, len=n)
     x <- rep(NA,n)
     u <- runif(n)
     xi0 <- which(xi == 0)
     xi1 <- which(xi != 0)
     x[xi0] <- mu[xi0] - sigma[xi0] * log(u[xi0])
     x[xi1] <- mu[xi1] + sigma[xi1] *
          (u[xi1]^(-xi[xi1] - 1) / xi[xi1])
     return(x)
     }

I might be misunderstanding, but when we set xi=0 and manipulate sigma, the answer varies. When xi=0, the density should be -(x - mu)/sigma, if I have that right.

> dgpd(1, 0, sigma=1, 0)
[1] 0.36788
> dgpd(1, 0, sigma=2, 0)
[1] 0.60653

**Comment by Bramstang** [comment]
Okay, so I finally figured it out! Our version of dgpd was off by a factor
of sigma if xi == 0, compared to Matlab and the two other packages. So I
took a second look on the wikipedia page and in the definition part, I
believe there is actually a factor 1/sigma missing (they have however
included it in the characterization part further down on the page). So
after adding that factor, our dgpd now agrees with Matlab and the two other
packages.

Here's the code:

dgpd <- function(x, mu, sigma, xi, log=FALSE)
    {
      x <- as.vector(x)
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      xi <- as.vector(xi)
      if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
      NN <- max(length(x), length(mu), length(sigma), length(xi))
      x <- rep(x, len=NN); mu <- rep(mu, len=NN)
      sigma <- rep(sigma, len=NN); xi <- rep(xi, len=NN)
      xi.ge.0 <- which(xi >= 0)
      xi.lt.0 <- which(xi < 0)
      if(any(mu[xi.ge.0] > x[xi.ge.0]) |
           any(mu[xi.lt.0] < x[xi.lt.0] + sigma[xi.lt.0] / xi[xi.lt.0]))
        stop("Parameter mu is outside of support.")
      z <- (x - mu) / sigma
      xi0 <- which(xi == 0)
      xi1 <- which(xi != 0)
      dens <- rep(NA, NN)
      dens[xi0] <- -z[xi0] - log(sigma[xi0])
      dens[xi1] <- log(1/sigma[xi1]) + log(1 + xi[xi1] *
                                             z[xi1]) * (-1/xi[xi1] - 1)
      if(log == FALSE) dens <- exp(dens)
      return(dens)
    }

Sidenote: the "Parameter mu is outside of support" message is perhaps a bit
misleading. It's more like the whole combination of parameters makes the
value impossible?

2015-03-20 13:52 GMT+01:00 Statisticat <notifications@github.com>:

**Comment by Bramstang** [comment]
Update: I took a look at the rgpd too, there was a typo there, a
parenthesis was misplaced. Also I slightly modified the support check in
the dgpd so that the check for minimum mu was included in both cases (ksi
== 0 and ksi != 0). I think everything is correct now! I ran some tests,
but there is of course the possibility that I overlooked something!

dgpd <- function(x, mu, sigma, xi, log=FALSE)
    {
      x <- as.vector(x)
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      xi <- as.vector(xi)
      if(any(sigma <= 0)) stop("The sigma parameter must be positive.")
      NN <- max(length(x), length(mu), length(sigma), length(xi))
      x <- rep(x, len=NN); mu <- rep(mu, len=NN)
      sigma <- rep(sigma, len=NN); xi <- rep(xi, len=NN)
      xi.ge.0 <- which(xi >= 0)
      xi.lt.0 <- which(xi < 0)
      if(any(mu > x) |
           any(mu[xi.lt.0] < x[xi.lt.0] + sigma[xi.lt.0] / xi[xi.lt.0]))
        stop("Parameter mu is outside of support.")
      z <- (x - mu) / sigma
      xi0 <- which(xi == 0)
      xi1 <- which(xi != 0)
      dens <- rep(NA, NN)
      dens[xi0] <- -z[xi0] - log(sigma[xi0])
      dens[xi1] <- log(1/sigma[xi1]) + log(1 + xi[xi1] *
                                             z[xi1]) * (-1/xi[xi1] - 1)
      if(log == FALSE) dens <- exp(dens)
      return(dens)
    }

    rgpd <- function(n, mu, sigma, xi)
    {
      mu <- as.vector(mu)
      sigma <- as.vector(sigma)
      xi <- as.vector(xi)
      if(any(sigma <= 0)) stop("The sigma parameter must be non-negative.")
      mu <- rep(mu, len=n); sigma <- rep(sigma, len=n)
      xi <- rep(xi, len=n)
      x <- rep(NA,n)
      u <- runif(n, min=0.001)
      xi0 <- which(xi == 0)
      xi1 <- which(xi != 0)
      x[xi0] <- mu[xi0] - sigma[xi0] * log(u[xi0])
      x[xi1] <- mu[xi1] + sigma[xi1] *
        (u[xi1]^(-xi[xi1]) - 1) / xi[xi1]
      return(x)
    }

2015-03-20 15:10 GMT+01:00 Philip Bramstång <philipbramstang@gmail.com>:

**Comment by Statisticat** [comment]
That looks great. And like you noted, the message about mu is not well phrased, and should probably be "x is out of support." I will test these on a few models and include them. Many thanks.
