### ISSUE TITLE
Is it possible to have a variable that changes the number of data points?

### ISSUE THREAD

**Issue by samedii** [Statisticat/LaplacesDemon#27]
Then using DIC to chose between the models?

**Comment by Statisticat** [comment]
Could you elaborate on that? DIC is comparable when the data is the same, not different, unless I'm missing something or you mean something different?

**Comment by samedii** [comment]
I would like to take block maxima of size k from a data set and let the MCMC algorithm find k as well as other variables.

I see, I'm looking at DIC at the moment and I thought it took into consideration the sample size like BIC seems to do.

**Comment by Statisticat** [comment]
I'm not sure if CPO (Conditional Predictive Ordinate) is what you are looking for or not, but you could use that to let MCMC tell you which sample to drop, maybe, depending on your specific goals of course. It sounds like you'd like to let MCMC tell you which is the best sub-sample of data by deviance, and drop the worst?

**Comment by samedii** [comment]
I don't think CPO is the same.

The idea:
* Sample of size n split into blocks, each of size k
* Data input to LD are the maxima of these blocks
* This data will be GEV distributed for large enough n and k
* MCMC to find GEV parameters and k (where LL must be compensated for sample size differences)

**Comment by Statisticat** [comment]
Yeah, that's different.
Maybe a model-based clustering scheme where each cluster (block) must have the same k, and the algorithm is about where to put each record, which would minimize deviance? Maybe a GEV-violating metric would have to be built in? That's an interesting situation...
